package_format_version = '1'
module_name = 'CMR Cistude'
module_code = 'cmr_cistude'
module_version = '1.0.0'
min_geonature_version = '2.4.0'
max_geonature_version = '3.0.0'
exclude_geonature_versions = []
